apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  init-mongo.sh: |
    #!/bin/bash
    mongo <<EOF
    db.getSiblingDB("unifi").createUser({user: "$MONGO_USER", pwd: "$MONGO_PASS", roles: [{role: "dbOwner", db: "unifi"}]}); 
    db.getSiblingDB("unifi_stat").createUser({user: "$MONGO_USER", pwd: "$MONGO_PASS", roles: [{role: "dbOwner", db: "unifi_stat"}]});
    EOF

