apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - name: unifi
        image: lscr.io/linuxserver/unifi-network-application:amd64-8.1.127-ls46

        volumeMounts:
        - name: unifi-data
          mountPath: /config
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username

        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password

        # - name: MONGO_PASS
        #   value: "password"
        # - name: MONGO_USER
        #   value: "unifi"
              
        - name: MONGO_DBNAME
          value: unifi
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_HOST
          value: mongodb

      volumes:
      - name: unifi-data
        persistentVolumeClaim:
          claimName: unifi

