apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.1.24
  labels:
    app: unifi
  name: unifi-tcp
spec:
  ports:
  - name: devicecom
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: webapi
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: httpredirects
    port: 8880
    protocol: TCP
    targetPort: 8880
  - name: httpsredirects
    port: 8843
    protocol: TCP
    targetPort: 8843
  - name: speedtest
    port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: unifi
  sessionAffinity: None
  type: LoadBalancer



